
version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

    volumes: 
      - ./cache:/data
volumes:
  cache:
    driver: local