FROM quay.io/redhattraining/httpd-parent:2.4

RUN yum install -y httpd && \
    yum clean all

RUN echo "Hello from the httpd-parent container!" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]